# Generated by Django 3.1.7 on 2022-09-21 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220921_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='questionansweroption',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionansweroption',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswertype',
            name='name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
