# Generated by Django 3.1.7 on 2022-09-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220921_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.questionanswertype'),
            preserve_default=False,
        ),
    ]
