# Generated by Django 3.1.7 on 2022-09-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='api.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='responds_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.questionnaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='responds_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='response',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='response_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.questionnaireresponse'),
            preserve_default=False,
        ),
    ]
